### ISSUE TITLE
apm Select AttributeGroup 404

### ISSUE THREAD

**Issue by dtbdtb** [rafal-szypulka/grafana-ibm-apm#10] opened 2017-11-04 07:56 UTC
hi
we have installed the latest grafana in linux
and we use apm datasource
and today we found we can test datasource ok.
but when we delete a datasource query and create a new
but we can not choose agent type
why ?
we can find agent type list when we click ,and we choose,but can not work ,
why ?but we can test apm datasource succeded,why ?
log:
t=2017-11-03T14:13:39+0800 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path="/api/datasources/proxy/2/datasources/Select Agent Type.../datasets/Select AttributeGroup.../columns" status=404 remote_addr=127.0.0.1 time_ms=35 size=7807 referer=

in fact we have found such error sometimes,but can not find where is wrong.
can anybody give us some hints?
i think is apm plugin is not so stable?

**Comment by rafal-szypulka** [comment] 2017-11-05 09:54
Plugin was tested with Grafana 4.5.2, please use this version until I make the plugin fully compatible with the Grafana 4.6

**Comment by rafal-szypulka** [comment] 2017-11-05 13:15
closed as duplicate of #9

**Closed by rafal-szypulka** 2017-11-05 13:15 UTC
